change baselines
conghaowoooong/Project-Gaia pull request #3
Opened 2021-09-01 02:59 UTC by conghaowoooong

change baselines in section 4.3 and table 1

2021-09-01 03:17 UTC, conghaowoooong commented
- 删除 Y-net (From goals, waypoints, ...) 实验结果，但是保持引用
- 添加cvpr2021两个方法的结果

2021-09-02 01:55 UTC, conghaowoooong commented
<img width="687" alt="截屏2021-09-02 上午9 55 15" src="https://user-images.githubusercontent.com/27466148/131768890-202bf393-47d9-41f7-8136-011fe96bcd40.png">

数据表格改成这样⬆️

2021-09-02 02:27 UTC, conghaowoooong commented
因为分支重命名会关闭这个pr，后续关于实验的定量分析都在这个分支修改
@NorthOcean

2021-09-06 21:50 UTC, NorthOcean approved these changes

2021-09-06 21:51 UTC, NorthOcean approved these changes

2021-09-06 21:54 UTC, NorthOcean approved these changes

2021-09-06 21:59 UTC, NorthOcean approved these changes

2021-09-06 22:00 UTC, NorthOcean approved these changes

2021-09-07 00:31 UTC, NorthOcean requested changes

2021-09-07 00:31 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +Compared with study No. 3 (which guides linear interpolation to finish predicting), its ADE and FDE have improved over 7\%.
Compared with study No. 3 which utilizes linear interpolation, its ADE and FDE have improved over 7\%.

2021-09-07 00:31 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +Compared with study No. 3 (which guides linear interpolation to finish predicting), its ADE and FDE have improved over 7\%.
语态没统一，有的是 ade and fde have been improved 有的是 ade and fde have improved.

2021-09-07 00:31 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +Besides, the most significant difference with the linear interpolation is that the \BETAMODEL~brings better non-linearity and society to the prediction with the help of the transformer skeleton and t
society?

2021-09-07 00:31 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +While a larger $K_c$ may require sufficient training data to tune each category's generator and even cause different categories to distribute overlap.
这个地方如果用while，就要和185整成一句话。
用成两句话要用 however。
However, a larger $K_c$ might require sufficient training data to tune the generator for each category, resulting in overlapping distributions of different categories.

2021-09-07 00:31 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +While a larger $K_c$ may require sufficient training data to tune each category's generator and even cause different categories to distribute overlap.
这个地方如果用while，就要和185整成一句话。
用成两句话要用 however

2021-09-07 00:31 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +Results illustrate that \MODEL~performs better when setting a higher $K_c$ on both \ETHUCY~and SDD.
从句和主句主语不一致，独立主格结构要求主语一致。
Results illustrate that \MODEL~performs better with a higher $K_c$ on both \ETHUCY~and SDD.
或者 We find that \MODEL~performs better when setting a higher $K_c$ on both \ETHUCY~and SDD.

2021-09-07 00:31 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +\FIG{fig_a_k} shows the ADE changing of \MODELG~with different $K_c$ and $K$ settings on SDD\footnote{Results of \PECNET~are pickled from Fig.5 in their paper \cite{mangalam2020not}.}.
\FIG{fig_a_k}\footnote{Results of \PECNET~are pickled from Fig.5 in the corresponding paper \cite{mangalam2020not}.} shows the changing of \MODELD~ADE (the red line) with different $K_c$ on SDD.

2021-09-07 00:31 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +Compared with one of the current SDD \SOTA~\PECNET, \MODELG~($K_c = 20$) improves its ADE for over 41.4\% when generating a large amount ($N = KK_c = 1000$) of trajectories.
196这句话应该和198这句话互换

2021-09-07 00:31 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +It shows that \MODEL~may achieve better performance with a lower $N$ quickly.
\MODEL~may achieve better performance with a lower $N$ quickly, thus greatly saving computing resources.

2021-09-07 00:31 UTC, NorthOcean commented on satoshi_aaai/contents/fig_a_k.tex
> +        $N$ represents the number of output trajectories, i.e., $N = KK_c$.
$N = K \tmies K_c$

2021-09-07 01:14 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +See details in \TABLE{tab_ade_all} and \TABLE{tab_ade_sdd}.
改成了两句
> We show the performance comparisons with other \SOTA~approaches on \ETHUCY~and SDD with the \emph{best-of-20} validation.
> See details in \TABLE{tab_ade_all} and \TABLE{tab_ade_sdd}.

2021-09-07 01:16 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +We show the \MODELD~results with $K_c = 20$ in \TABLE{tab_ade_all}.
把它当做一个默认的超参数那种的吗？
那样就可以全程忽略掉K_c，只在details里说设置

2021-09-07 01:20 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +The average ADE of \MODELD~is almost the same as the \SOTA~\TRAJECTRONPP~on \ETHUCY, while the average FDE has been improved for over 10.2\%.
`gains`用的好

2021-09-07 01:22 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +It still lacks uncertain factors when implementing, which means that its results could not be directly compared with generative models with the same number of generations (such as $K_c = 20$ \MODELD~
删除了后半句

> Note that \MODELD is \emph{deterministic}, even if it could output a variety of predictions at the same time.
> It still lacks uncertain factors when implementing.
> Nevertheless, its results on \ETHUCY~show that it has strong competitiveness even with these generative models when generating the same number of trajectories $K_c = K =20$.

2021-09-07 01:24 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +Results show that \MODELD~($K_c=20$) outperforms 13.3\% ADE and 20.6\% FDE compared with the \SOTA~LB-EBM on SDD.
`margin`用的好

2021-09-07 01:34 UTC, conghaowoooong commented
> However, it still surpasses the existing \SOTA~methods' ADE or FDE on several \ETHUCY~sub-datasets and SDD even with the \emph{best-of-20} validation.

在数据集前面用in还是on在写的时候就一直很混乱，凭感觉用的。
这里需不需要统一 @NorthOcean

2021-09-07 01:35 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +Please see ``Quantitative Analysis'' in Section 4.5.
最后一起修改，已标记 TODO

2021-09-07 01:38 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +Their results are shown in \TABLE{tab_a_k} and \FIG{fig_a_k}.
修改后的句子好像太复杂了

2021-09-07 01:39 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +Compared with the \SOTA~single-output Transformer-based method \TRANSFORMER~\cite{yu2020spatio}, the average ADE and FDE have been improved up to 56\% and 81\% on \ETHUCY.
这里虽然已经删除了但是还需要把这个消融实验和其他的比较吗
因为考虑的是和single-output模型比较起来是最方便的

2021-09-07 01:41 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +The beta model takes the agent's destination planning as the embodiment of their activity style to make stylized predictions.
这一段说的是`风格假设`+`风格化预测`两者一起的过程，防止和后边的`风格化预测`混淆起了这个名字，看起来还是容易混淆。需要再换一个说法

2021-09-07 01:45 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +Compared with study No. 3 (which guides linear interpolation to finish predicting), its ADE and FDE have improved over 7\%.
这里ADE/FDE是提高还是被提高？

2021-09-07 01:47 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +Besides, the most significant difference with the linear interpolation is that the \BETAMODEL~brings better non-linearity and society to the prediction with the help of the transformer skeleton and t
大概意思指交互行为，需要换一个词

2021-09-07 01:51 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +Results illustrate that \MODEL~performs better when setting a higher $K_c$ on both \ETHUCY~and SDD.
换成了前者

2021-09-07 01:57 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +It shows that \MODEL~may achieve better performance with a lower $N$ quickly.
`greatly saving computing resources`说法需要斟酌

2021-09-07 01:59 UTC, conghaowoooong commented on satoshi_aaai/contents/fig_a_k.tex
> +        $N$ represents the number of output trajectories, i.e., $N = KK_c$.
在别人的文章好像很少看到字母之间用乘号，待确认

2021-09-09 01:42 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +We run the following experiments and analysis to verify the performance of each designs and further present how these components work in \MODEL.
We conduct the following experiments and analyses to verify the performance of each design and to further present how these components work in \MODEL.

2021-09-09 01:42 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +Study No. 2 show that its performance is even comparable to \PECNET \cite{mangalam2020not} with only a slight performance difference (approximately 3-4\% on ADE and FDE) when the simple linear interp
135，136，137连续出现3个show
show - demonstrates

2021-09-09 01:42 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +\FIG{fig_2stages}(a) shows an example of the given planning hypothesises.
shows - provides

2021-09-09 01:42 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +Besides, the most significant difference with No. 2 is that it brings better non-linearity and society to the prediction with the help of the transformer skeleton and the context map.
difference with - difference from
society ？？

2021-09-09 01:42 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +However, a larger $K_c$ may require sufficient training data to tune each category's generator and even cause different categories to distribute overlap.
However, a larger $K_c$ might require sufficient training data to tune the generator for each category, resulting in overlapping distributions of different categories.

2021-09-09 01:42 UTC, NorthOcean commented on satoshi_aaai/contents/experiments.tex
> +We show the \MODELG~($K_c = 20$) performance comparison in \TABLE{tab_a_k} among several $k$.
We present the performance comparison of \MODELG~($K_c = 20$) between several $k$ in TABLE{tab_a_k}.

2021-09-09 01:55 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +Besides, the most significant difference with No. 2 is that it brings better non-linearity and society to the prediction with the help of the transformer skeleton and the context map.
符合社交规范的，我还没想好用什么

2021-09-09 01:56 UTC, conghaowoooong commented on satoshi_aaai/contents/experiments.tex
> +However, a larger $K_c$ may require sufficient training data to tune each category's generator and even cause different categories to distribute overlap.
`resulting in ...`后半句删掉了

2021-09-09 02:14 UTC, merged